<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">
<glsa id="201309-05">
  <title>pip: Multiple vulnerabilities</title>
  <synopsis>Multiple vulnerabilities have been found in pip, which may allow
    remote attackers to execute arbitrary code or local attackers to conduct
    symlink attacks.
  </synopsis>
  <product type="ebuild">pip</product>
  <announced>2013-09-12</announced>
  <revised count="1">2013-09-12</revised>
  <bug>462616</bug>
  <bug>480202</bug>
  <access>local, remote</access>
  <affected>
    <package name="dev-python/pip" auto="yes" arch="*">
      <unaffected range="ge">1.3.1</unaffected>
      <vulnerable range="lt">1.3.1</vulnerable>
    </package>
  </affected>
  <background>
    <p>pip is a tool for installing and managing Python packages.</p>
  </background>
  <description>
    <p>Multiple vulnerabilities have been discovered in pip. Please review the
      CVE identifiers referenced below for details.
    </p>
  </description>
  <impact type="normal">
    <p>A remote attacker could conduct a Man-in-the-Middle attack to cause pip
      to execute arbitrary code. A local attacker could perform symlink attacks
      to overwrite arbitrary files with the privileges of the user running the
      application.
    </p>
  </impact>
  <workaround>
    <p>There is no known workaround at this time.</p>
  </workaround>
  <resolution>
    <p>All pip users should upgrade to the latest version:</p>
    
    <code>
      # emerge --sync
      # emerge --ask --oneshot --verbose "&gt;=dev-python/pip-1.3.1"
    </code>
    
  </resolution>
  <references>
    <uri link="https://nvd.nist.gov/nvd.cfm?cvename=CVE-2013-1629">CVE-2013-1629</uri>
    <uri link="https://nvd.nist.gov/nvd.cfm?cvename=CVE-2013-1888">CVE-2013-1888</uri>
  </references>
  <metadata tag="requester" timestamp="2013-07-11T20:41:57Z">
    keytoaster
  </metadata>
  <metadata tag="submitter" timestamp="2013-09-12T20:57:59Z">
    creffett
  </metadata>
</glsa>
