<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">
<glsa id="202301-03">
    <title>scikit-learn: Denial of Service</title>
    <synopsis>A vulnerability was found in scikit-learn which could result in denial of service.</synopsis>
    <product type="ebuild">scikit-learn</product>
    <announced>2023-01-11</announced>
    <revised count="1">2023-01-11</revised>
    <bug>758323</bug>
    <access>remote</access>
    <affected>
        <package name="sci-libs/scikit-learn" auto="yes" arch="*">
            <unaffected range="ge">1.1.1</unaffected>
            <vulnerable range="lt">1.1.1</vulnerable>
        </package>
    </affected>
    <background>
        <p>scikit-learn is a machine learning library for Python.</p>
    </background>
    <description>
        <p>When supplied with a crafted model SVM, predict() can result in a null pointer dereference.</p>
    </description>
    <impact type="low">
        <p>An attcker capable of providing a crafted model to scikit-learn can result in denial of service.</p>
    </impact>
    <workaround>
        <p>There is no known workaround at this time.</p>
    </workaround>
    <resolution>
        <p>All scikit-learn users should upgrade to the latest version:</p>
        
        <code>
          # emerge --sync
          # emerge --ask --oneshot --verbose ">=sci-libs/scikit-learn-1.1.1"
        </code>
    </resolution>
    <references>
        <uri link="https://nvd.nist.gov/vuln/detail/CVE-2020-28975">CVE-2020-28975</uri>
    </references>
    <metadata tag="requester" timestamp="2023-01-11T05:16:33.475780Z">ajak</metadata>
    <metadata tag="submitter" timestamp="2023-01-11T05:16:33.478230Z">ajak</metadata>
</glsa>