<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glsa SYSTEM "http://www.gentoo.org/dtd/glsa.dtd">
<glsa id="202008-01">
  <title>Python: Multiple vulnerabilities</title>
  <synopsis>Multiple vulnerabilities have been found in Python, the worst of
    which could result in a Denial of Service condition.
  </synopsis>
  <product type="ebuild">python</product>
  <announced>2020-08-02</announced>
  <revised count="1">2020-08-02</revised>
  <bug>728668</bug>
  <bug>732498</bug>
  <access>remote</access>
  <affected>
    <package name="dev-lang/python" auto="yes" arch="*">
      <unaffected range="ge" slot="2.7">2.7.18-r1</unaffected>
      <unaffected range="ge" slot="3.6">3.6.11-r2</unaffected>
      <unaffected range="ge" slot="3.7">3.7.8-r2</unaffected>
      <unaffected range="ge" slot="3.8">3.8.4-r1</unaffected>
      <vulnerable range="lt" slot="2.7">2.7.18-r1</vulnerable>
      <vulnerable range="lt" slot="3.6">3.6.11-r2</vulnerable>
      <vulnerable range="lt" slot="3.7">3.7.8-r2</vulnerable>
      <vulnerable range="lt" slot="3.8">3.8.4-r1</vulnerable>
    </package>
  </affected>
  <background>
    <p>Python is an interpreted, interactive, object-oriented programming
      language.
    </p>
  </background>
  <description>
    <p>Multiple vulnerabilities have been discovered in Python. Please review
      the CVE identifiers referenced below for details.
    </p>
  </description>
  <impact type="normal">
    <p>Please review the referenced CVE identifiers for details.</p>
  </impact>
  <workaround>
    <p>There is no known workaround at this time.</p>
  </workaround>
  <resolution>
    <p>All Python 2.7 users should upgrade to the latest version:</p>
    
    <code>
      # emerge --sync
      # emerge --ask --oneshot --verbose "&gt;=dev-lang/python-2.7.18-r1"
    </code>
    
    <p>All Python 3.6 users should upgrade to the latest version:</p>
    
    <code>
      # emerge --sync
      # emerge --ask --oneshot --verbose "&gt;=dev-lang/python-3.6.11-r2"
    </code>
    
    <p>All Python 3.7 users should upgrade to the latest version:</p>
    
    <code>
      # emerge --sync
      # emerge --ask --oneshot --verbose "&gt;=dev-lang/python-3.7.8-r2"
    </code>
    
    <p>All Python 3.8 users should upgrade to the latest version:</p>
    
    <code>
      # emerge --sync
      # emerge --ask --oneshot --verbose "&gt;=dev-lang/python-3.8.4-r1"
    </code>
  </resolution>
  <references>
    <uri link="https://nvd.nist.gov/vuln/detail/CVE-2019-20907">CVE-2019-20907</uri>
    <uri link="https://nvd.nist.gov/vuln/detail/CVE-2020-14422">CVE-2020-14422</uri>
  </references>
  <metadata tag="requester" timestamp="2020-07-31T17:34:38Z">sam_c</metadata>
  <metadata tag="submitter" timestamp="2020-08-02T03:19:15Z">b-man</metadata>
</glsa>
